### ISSUE TITLE
[Memory managment] Deallocating GPU variables and freeing memory

### ISSUE THREAD

**Issue by mscipio** [mikgroup/sigpy#49] opened 2020-05-11 13:52 UTC
I don't know if this is of interest, or if you are aware of this behavior, but I thought I would mentioned it here, in case anyone was struggling with this "bug" ...

**Describe the bug**
When creating an instance of an 'app' class, we pass to the `__init__ `function all the input variables needed to create an instance of an 'alg'. If using a GPU, this sends a lot of data (i.e. coord, weights, ...) to the GPU's RAM memory. 
Running the `run()` method, we can then perform the optimization and get back the result. However, the memory allocated on the GPU is not freed automatically. Furthermore, even if we delete to instance of the app class, after completing the optimization, part of that memory remain allocated, untill we restart the python kernel. At least, this is what happens using python notebooks.

**A few notes:**
- the only algorithm no affected by this, which is able to correctly free GPU's memory is Conjugate Gradient. I haven't been able to figure out why.
- To check the memory used by your app you may do as follows:
 -- create a subclass of `sp.app.LinearLeastSquares`
 -- in the `__init__()` method add the following lines: 

```python
import cupy
self.mempool = cupy.get_default_memory_pool()
self.pinned_mempool = cupy.get_default_pinned_memory_pool()
```
 -- then define a `_post_update(self)` method as:
```python
def _post_update(self):
        print(self.mempool.used_bytes())              
        print(self.mempool.total_bytes())             
        print(self.pinned_mempool.n_free_blocks())
        return
```
You will se that after each `alg.update()`, the memory occupancy keeps growing.
After the `run()` is finished you can delete the instance of the app, but such memory will remain flagged.

The only way I found so far to overcome this issue is to add a `del self.alg` to the `__output(self) `method of the app: 
```python
def _output(self):
        x = sp.to_device(self.x, sp.cpu_device)
        del self.x
        del self.alg
        return x
```
this seems like the only way to me to deallocate all the structures created by the algorithm on the GPU.

**Comment by frankong** [comment] 2020-07-23 05:00
Hi-- Sorry for the late reply.
This is something I'm not aware of, and can investigate more. Do you know if this also happen when you call the functions in a script?

**Comment by cth7** [comment] 2020-10-19 19:23
Not sure if anyone is still getting this issue, but it sounds like this isn't a bug, but rather is just the way python manages memory.

When you create arrays (CPU or GPU) your python program will get memory from the OS. When that array is no longer referenced, python may keep that memory in its memory pool for future arrays rather than returning it to the OS (for efficiency purposes). That is why used_bytes may drop to 0 after the array is no longer referenced (i.e. when you "delete" the app), but total_bytes remains the same; total_bytes shows the memory remaining in the memory pool of that python program. When you restart the python kernel, obviously all memory is returned to the OS.

If you need that memory returned to the OS right after the app finishes running, delete all references to that app (e.g. `app = None`), and then for CuPy you can do `mempool.free_all_blocks()`.

Personally I've noticed in some cases that python _will_ return memory to the OS as soon as the array is no longer referenced if the array is really large.

I hope this addresses your problem. See here for more information: https://docs.cupy.dev/en/stable/reference/memory.html

**Comment by cth7** [comment] 2020-10-27 00:16
Ah the situation may be more complicated than I thought. I found a memory leak in the ESPIRiT app caused by passing a reference to the app (i.e. self) to the alg (fixed it here https://github.com/mikgroup/sigpy/pull/66). @mscipio What other apps/algs were you getting this problem with?

**Comment by sidward** [comment] 2021-08-18 23:54
Hi @cth7,

I am closing this issue since the discussion has stagnated. However, if you have any more recommendations related to memory usage, please do post it below and I will be happy to look into them.

**Closed by sidward** 2021-08-18 23:54 UTC
Labels: bug
